// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGaatCoYR2AwJ6XW6d-Cd27ugpe6ZhLhs',
    appId: '1:832896093936:web:da83e56ebb0bb52fbabc35',
    messagingSenderId: '832896093936',
    projectId: 'c-me-project',
    authDomain: 'c-me-project.firebaseapp.com',
    storageBucket: 'c-me-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzFPvO9UX3G2w6bJjmfOn2bPeqWI64JOQ',
    appId: '1:832896093936:android:bc4f2d7534fb8e6ababc35',
    messagingSenderId: '832896093936',
    projectId: 'c-me-project',
    storageBucket: 'c-me-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpyZ9OIs7-JbBfn2rDkAbKOcezgfv2mH0',
    appId: '1:832896093936:ios:e2dab116e8d516acbabc35',
    messagingSenderId: '832896093936',
    projectId: 'c-me-project',
    storageBucket: 'c-me-project.firebasestorage.app',
    iosBundleId: 'com.example.x',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpyZ9OIs7-JbBfn2rDkAbKOcezgfv2mH0',
    appId: '1:832896093936:ios:e2dab116e8d516acbabc35',
    messagingSenderId: '832896093936',
    projectId: 'c-me-project',
    storageBucket: 'c-me-project.firebasestorage.app',
    iosBundleId: 'com.example.x',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGaatCoYR2AwJ6XW6d-Cd27ugpe6ZhLhs',
    appId: '1:832896093936:web:5a98b5c962ce0e0fbabc35',
    messagingSenderId: '832896093936',
    projectId: 'c-me-project',
    authDomain: 'c-me-project.firebaseapp.com',
    storageBucket: 'c-me-project.firebasestorage.app',
  );
}
